<a href="https://colab.research.google.com/github/izzoa222/python_programming/blob/main/%EA%B9%80%EA%B8%B0%EC%A0%952025191704_11%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np



In [3]:
a = np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [4]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [5]:
print(a[0])

1


In [6]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [7]:
a[:3]

array([10,  2,  3])

In [8]:
b=a[3:]
b

array([4, 5, 6])

In [9]:
b[0]=40
a

array([10,  2,  3, 40,  5,  6])

In [10]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [12]:
print(a[1,3])

8


In [13]:
a.ndim

2

In [15]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
a = np.array([[[1, 2, 3, 4], [ 5,  6,  7,  8]]])
a.ndim

3

In [17]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [18]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
a.ndim

2

In [20]:
a.shape

(3, 4)

In [21]:
len(a.shape) == a.ndim

True

In [22]:
a.size

12

In [23]:
import math
a.size == math.prod(a.shape)

True

In [24]:
a.dtype

dtype('int64')

In [25]:
np.zeros(2)

array([0., 0.])

In [26]:
np.ones(2)

array([1., 1.])

In [29]:
np.empty(2)

array([1., 1.])

In [30]:
np.arange(4)

array([0, 1, 2, 3])

In [31]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [32]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [33]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [37]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(arr)
np.sort(arr)

[2 1 5 3 7 4 6 8]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim

3

In [44]:
array_example.size

24

In [45]:
array_example.shape

(3, 2, 4)

In [46]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [47]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [50]:
np.reshape(a, (1,6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [51]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [52]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [53]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [54]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [55]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [56]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [57]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [59]:
data = np.array([1, 2, 3])

print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


In [61]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

[1 2 3 4]


In [62]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [63]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [64]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [65]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [69]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [70]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [71]:
print(a[b])

[1 2 3 4]


In [72]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [74]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [76]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [77]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [78]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [79]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [80]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [81]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [83]:
b1 = a[0, :]
print(b1)
b1[0] = 99
print(b1)
print(a)

[99  2  3  4]
[99  2  3  4]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [84]:
b2 = a.copy()

In [86]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
print(ones)
data + ones

[1 1]


array([2, 3])

In [87]:
print(data - ones)
print(data * data)
print(data / data)

[0 1]
[1 4]
[1. 1.]


In [89]:
a = np.array([1, 2, 3, 4])

print(a.sum())

10


In [91]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis=0)

array([3, 3])

In [92]:
b.sum(axis=0)

array([3, 3])

In [93]:
b.sum(axis=1)

array([2, 4])

In [94]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [96]:
print(data.max())
print(data.min())
print(data.sum())

2.0
1.0
3.0


In [97]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [101]:
print(a.sum())
print(a.min())
print(a.min(axis=0))

4.8595784
0.05093587
[0.12697628 0.05093587 0.26590556 0.5510652 ]


In [102]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [103]:
print(data[0, 1])
print(data[1:3])
print(data[0:2, 0])

2
[[3 4]
 [5 6]]
[1 3]


In [104]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [105]:
data = np.array([[1, 2], [5, 3], [4, 6]])
print(data)
print(data.max(axis=0))
print(data.max(axis=1))

[[1 2]
 [5 3]
 [4 6]]
[5 6]
[2 5 6]


In [107]:
data = np.array([[1, 2], [3, 4]])
print(data)
ones = np.array([[1, 1], [1, 1]])
print(ones)
print(data + ones)

[[1 2]
 [3 4]]
[[1 1]
 [1 1]]
[[2 3]
 [4 5]]


In [108]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [109]:
np.ones((4, 3, 2))




array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [113]:
print(np.ones(3))
print(np.zeros(3))
rng = np.random.default_rng()  # the simplest way to generate random numbers
print(rng.random(3))

[1. 1. 1.]
[0. 0. 0.]
[0.87303609 0.70108781 0.94111511]


In [115]:
print(np.ones((3, 2)))
print(np.zeros((3, 2)))
print(rng.random((3, 2)) )

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.25332198 0.56732541]
 [0.84742066 0.36979766]
 [0.05810204 0.81837506]]


In [116]:
rng.integers(5, size=(2, 4))

array([[1, 4, 4, 1],
       [3, 2, 1, 1]])

In [118]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [119]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [120]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [122]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [123]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [124]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)
print(indices)
print(occurrence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


In [126]:
print(data.reshape(2, 3))
print(data.reshape(3, 2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [127]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [129]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [130]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [132]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [134]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [135]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [136]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [137]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [138]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [139]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array
print(a1)  # New array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [140]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array
print(a2)  # New array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]
